# -*- coding: utf-8 -*-
"""
Created on Thu Feb 10 13:22:36 2022

dictionaries for variables and locations

@author: schne_la
"""

# How do I comment this correct?

# dictionary for the timeseries plot 
# add layer to dictionary 
# add minimum value as well
# add depth (surface and unknown)
varDict = {
        'Chlfa' : {'mod_vars' : 'Chlfa', 
                   'p35code' : 'EPC00105', 
                   'lab_vars' : 'CHLF-a (ug/L)', 
                   'out_vars' : 'CHLFa', 
                   'conv_vars' : 1.,
                   'depth' : 'sea level'},
        'NO3' : {'mod_vars' : 'NO3', 
                  'p35code' : 'EPC00004', 
                  'lab_vars' : 'NO\u2083 (mgN/l)', 
                  'out_vars' : 'NO3', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'NH4' : {'mod_vars' : 'NH4', 
                  'p35code' : 'EPC00009', 
                  'lab_vars' : 'NH\u2084 (mgN/l)', 
                  'out_vars' : 'NH4', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'DIN' : {'mod_vars' : 'DIN', 
                  'p35code' : 'EPC00198', 
                  'lab_vars' : 'DIN (mgN/l)', 
                  'out_vars' : 'DIN', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'PO4' : {'mod_vars' : 'PO4', 
                  'p35code' : 'EPC00007', 
                  'lab_vars' : 'PO\u2084 (mgP/l)', 
                  'out_vars' : 'PO4', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'Si' : {'mod_vars' : 'Si', 
                  'p35code' : 'EPC00008', 
                  'lab_vars' : 'Si (mgSi/L)', 
                  'out_vars' : 'Si', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'OXY' : {'mod_vars' : 'OXY', 
                  'p35code' : 'EPC00002', 
                  'lab_vars' : 'O\u2082 (mg/L)', 
                  'out_vars' : 'O2', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'IM1' : {'mod_vars' : 'IM1', 
                  'p35code' : 'EXTRA004', 
                  'lab_vars' : 'SPM (mg/L)', 
                  'out_vars' : 'SPM', 
                  'conv_vars' : 1.},
        'POC1' : {'mod_vars' : 'POC1', 
                  'p35code' : 'EPC00157', 
                  'lab_vars' : 'POC1 (mgC/l)', 
                  'out_vars' : 'POC1', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'PON' : {'mod_vars' : 'PON', 
                  'p35code' : 'EPC00212', 
                  'lab_vars' : 'PON (mgN/l)', 
                  'out_vars' : 'PON', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'POP1' : {'mod_vars' : 'POP1', 
                  'p35code' : 'EPC00201', 
                  'lab_vars' : 'POP1 (mgP/l)', 
                  'out_vars' : 'POP1', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'salinity' : {'mod_vars' : 'salinity', 
                  'p35code' : 'EPC00001', 
                  'lab_vars' : 'Salinity (g/kg)', 
                  'out_vars' : 'sal', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'temperature' : {'mod_vars' : 'temperature', 
                  'p35code' : 'WATERTEMP', 
                  'lab_vars' : 'Temperature (celcius)', 
                  'out_vars' : 'temp', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'TotN' : {'mod_vars' : 'TotN', 
                  'p35code' : 'EPC00134', 
                  'lab_vars' : 'TotN (mgN/l)', 
                  'out_vars' : 'TotN', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'TotP' : {'mod_vars' : 'TotP', 
                  'p35code' : 'EPC00135', 
                  'lab_vars' : 'TotP (mgP/l)', 
                  'out_vars' : 'TotP', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'pH' : {'mod_vars' : 'pH', 
                  'p35code' : 'EPC00168', 
                  'lab_vars' : 'pH', 
                  'out_vars' : 'pH', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'pCO2water' : {'mod_vars' : 'pCO2water', 
                  'p35code' : 'EPC00133', 
                  'lab_vars' : 'pCO2 (microatms)', 
                  'out_vars' : 'pCO2', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'ExtVl' : {'mod_vars' : 'ExtVl', 
                  'p35code' : 'EXTRA002', 
                  'lab_vars' : 'extinction (1/m)', 
                  'out_vars' : 'Ext', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'O2_bottom' : {'mod_vars' : 'OXY', 
                  'p35code' : 'EPC00002', 
                  'lab_vars' : 'O\u2082 (mg/L)', 
                  'out_vars' : 'O2_bottom', 
                  'conv_vars' : 1.,
                  'depth' : 'sea level'},
        'PP' : {'mod_vars' : 'fPPtot', 
                  'p35code' : 'INPPPIC1', 
                  'lab_vars' : 'PP (mgC/m2/d)', 
                  'out_vars' : 'PP', 
                  'conv_vars' : 1000.,
                  'depth' : 'sea level'}
}

varDict_TS = {
        'Chlfa' : {'mod_vars' : 'Chlfa', 
                   'p35code' : 'EPC00105', 
                   'lab_vars' : 'CHLF-a (ug/L)', 
                   'out_vars' : 'CHLFa', 
                   'conv_vars' : 1.,
                   'depth' : ['sea level', 'unknown']},
        'NO3' : {'mod_vars' : 'NO3', 
                  'p35code' : 'EPC00004', 
                  'lab_vars' : 'NO\u2083 (mgN/l)', 
                  'out_vars' : 'NO3', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']},
        'NH4' : {'mod_vars' : 'NH4', 
                  'p35code' : 'EPC00009', 
                  'lab_vars' : 'NH\u2084 (mgN/l)', 
                  'out_vars' : 'NH4', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']},
        'DIN' : {'mod_vars' : 'DIN', 
                  'p35code' : 'EPC00198', 
                  'lab_vars' : 'DIN (mgN/l)', 
                  'out_vars' : 'DIN', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']},
        'PO4' : {'mod_vars' : 'PO4', 
                  'p35code' : 'EPC00007', 
                  'lab_vars' : 'PO\u2084 (mgP/l)', 
                  'out_vars' : 'PO4', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']},
        'Si' : {'mod_vars' : 'Si', 
                  'p35code' : 'EPC00008', 
                  'lab_vars' : 'Si (mgSi/L)', 
                  'out_vars' : 'Si', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']},
        'IM1' : {'mod_vars' : 'IM1', 
                  'p35code' : 'EXTRA004', 
                  'lab_vars' : 'SPM (mg/L)', 
                  'out_vars' : 'SPM', 
                  'conv_vars' : 1.,
		  'depth' : ['sea level', 'unknown']},
        'salinity' : {'mod_vars' : 'salinity', 
                  'p35code' : 'EPC00001', 
                  'lab_vars' : 'Salinity (g/kg)', 
                  'out_vars' : 'sal', 
                  'conv_vars' : 1.,
                  'depth' : ['sea level', 'unknown']}
}

# plot locations in NWDM and model output
plot_locs = ['NOORDWK1','NOORDWK10','NOORDWK2','NOORDWK20','NOORDWK30','NOORDWK4','NOORDWK50','NOORDWK70',
              'ROTTMPT10','ROTTMPT100','ROTTMPT15','ROTTMPT20','ROTTMPT3','ROTTMPT30','ROTTMPT5','ROTTMPT50',
              'ROTTMPT70', 'TERSLG10','TERSLG100', 'TERSLG135','TERSLG175','TERSLG20','TERSLG235','TERSLG30',
              'TERSLG4','TERSLG50','TERSLG70', 'WALCRN1','WALCRN10','WALCRN2','WALCRN20','WALCRN30','WALCRN4',
              'WALCRN50','WALCRN70', '220006','220017','220052_B','220052_S','220057','220065','Nney_W_1',
              'Nney_W_2', 'Nney_W_3','WeMu_W_1','WeMu_W2','Wu_KU-W1','ZOUTKPLZGT','ZUIDOLWOT','BOCHTVWTM',
              'BOOMKDP','DANTZGT','DOOVBWT', 'GROOTGND', 'HUIBGOT', 'MARSDND', 'VLIESM','Vlissingen_boei_SSVH',
              'JaBu_W_1','Bork_W_1', 'DOWSING', 'J1', 'J12', 'LIVBAY', 'M388', 'M394', 'M397',
              'M435', 'M55', 'M57',  'M765', 'N14_FALKENBERG', 'Point_2_SRN_Boulogne', 'P2', 'St._Peter_Eider',
              'TH1', 'W04', 'W05', 'A17', 'AMO_6', 'ANHOLTE', 'UKO1']

# column names in in-situ database (use for measurement_view_all)
columnsNWDM = ("location_code", "date", "depth", "vertical_reference_preflabel",
            "vertical_reference_code", "p35code", "p35preflabel", 
            "value", "unit_preflabel", "quality_code", "station", "geom")


